package br.telehand.model;


//Generated 09/04/2014 16:06:53 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
* VwAgendaComAgendamento generated by hbm2java
*/
@Entity
@Table(name = "vw_agenda_com_agendamento", catalog = "db_sge")
public class VwAgendaComAgendamento implements java.io.Serializable {

	private VwAgendaComAgendamentoId id;

	public VwAgendaComAgendamento() {
	}

	public VwAgendaComAgendamento(VwAgendaComAgendamentoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idServico", column = @Column(name = "id_servico", nullable = false)),
			@AttributeOverride(name = "idJanela", column = @Column(name = "id_janela", nullable = false)),
			@AttributeOverride(name = "idEquipe", column = @Column(name = "id_equipe", nullable = false)),
			@AttributeOverride(name = "hrInicial", column = @Column(name = "Hr_inicial", nullable = false, length = 0)),
			@AttributeOverride(name = "hrFinal", column = @Column(name = "Hr_final", nullable = false, length = 0)),
			@AttributeOverride(name = "idAtendimento", column = @Column(name = "id_atendimento", nullable = false)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 19)) })
	public VwAgendaComAgendamentoId getId() {
		return this.id;
	}

	public void setId(VwAgendaComAgendamentoId id) {
		this.id = id;
	}

}
