package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwDadosRhId generated by hbm2java
 */
@Embeddable
public class VwDadosRhId implements java.io.Serializable {

	private int nrMatricula;
	private String nmEmpregado;
	private Date dtInicioIndisp;
	private Date dtFimIndisp;

	public VwDadosRhId() {
	}

	public VwDadosRhId(int nrMatricula, String nmEmpregado) {
		this.nrMatricula = nrMatricula;
		this.nmEmpregado = nmEmpregado;
	}

	public VwDadosRhId(int nrMatricula, String nmEmpregado,
			Date dtInicioIndisp, Date dtFimIndisp) {
		this.nrMatricula = nrMatricula;
		this.nmEmpregado = nmEmpregado;
		this.dtInicioIndisp = dtInicioIndisp;
		this.dtFimIndisp = dtFimIndisp;
	}

	@Column(name = "NR_MATRICULA", nullable = false)
	public int getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(int nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	@Column(name = "NM_EMPREGADO", nullable = false, length = 20)
	public String getNmEmpregado() {
		return this.nmEmpregado;
	}

	public void setNmEmpregado(String nmEmpregado) {
		this.nmEmpregado = nmEmpregado;
	}

	@Column(name = "dt_inicio_indisp", length = 0)
	public Date getDtInicioIndisp() {
		return this.dtInicioIndisp;
	}

	public void setDtInicioIndisp(Date dtInicioIndisp) {
		this.dtInicioIndisp = dtInicioIndisp;
	}

	@Column(name = "dt_fim_indisp", length = 0)
	public Date getDtFimIndisp() {
		return this.dtFimIndisp;
	}

	public void setDtFimIndisp(Date dtFimIndisp) {
		this.dtFimIndisp = dtFimIndisp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwDadosRhId))
			return false;
		VwDadosRhId castOther = (VwDadosRhId) other;

		return (this.getNrMatricula() == castOther.getNrMatricula())
				&& ((this.getNmEmpregado() == castOther.getNmEmpregado()) || (this
						.getNmEmpregado() != null
						&& castOther.getNmEmpregado() != null && this
						.getNmEmpregado().equals(castOther.getNmEmpregado())))
				&& ((this.getDtInicioIndisp() == castOther.getDtInicioIndisp()) || (this
						.getDtInicioIndisp() != null
						&& castOther.getDtInicioIndisp() != null && this
						.getDtInicioIndisp().equals(
								castOther.getDtInicioIndisp())))
				&& ((this.getDtFimIndisp() == castOther.getDtFimIndisp()) || (this
						.getDtFimIndisp() != null
						&& castOther.getDtFimIndisp() != null && this
						.getDtFimIndisp().equals(castOther.getDtFimIndisp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNrMatricula();
		result = 37
				* result
				+ (getNmEmpregado() == null ? 0 : this.getNmEmpregado()
						.hashCode());
		result = 37
				* result
				+ (getDtInicioIndisp() == null ? 0 : this.getDtInicioIndisp()
						.hashCode());
		result = 37
				* result
				+ (getDtFimIndisp() == null ? 0 : this.getDtFimIndisp()
						.hashCode());
		return result;
	}

}
