package br.telehand.model;

// Generated 27/03/2014 16:20:36 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwDadosRh generated by hbm2java
 */
@Entity
@Table(name = "vw_dados_rh", catalog = "db_sge")
public class VwDadosRh implements java.io.Serializable {

	private VwDadosRhId id;

	public VwDadosRh() {
	}

	public VwDadosRh(VwDadosRhId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrMatricula", column = @Column(name = "NR_MATRICULA", nullable = false)),
			@AttributeOverride(name = "nmEmpregado", column = @Column(name = "NM_EMPREGADO", nullable = false, length = 20)),
			@AttributeOverride(name = "dtInicioIndisp", column = @Column(name = "dt_inicio_indisp", length = 0)),
			@AttributeOverride(name = "dtFimIndisp", column = @Column(name = "dt_fim_indisp", length = 0)) })
	public VwDadosRhId getId() {
		return this.id;
	}

	public void setId(VwDadosRhId id) {
		this.id = id;
	}

}
